theme = 'congo'
baseURL = 'https://travels.loganfamily.co.uk/'
locale = 'en-gb'
title = 'Logan Van Travels'
summaryLength = 25

[permalinks]
  campervan = '/:slug/'
  holidays = '/:slug/'
  pages = '/pages/:slug/'
