[[main]]
  identifier = "campervan"
  name = "Campervan"
  url = "/campervan/"
  weight = 10

[[main]]
  parent = "campervan"
  name = "All"
  url = "/campervan/"
  weight = 10

[[main]]
  parent = "campervan"
  name = "Aire"
  url = "/site-types/aire/"
  weight = 20

[[main]]
  parent = "campervan"
  name = "Independent"
  url = "/site-types/independent/"
  weight = 30

[[main]]
  name = "About"
  url = "/pages/about/"
  weight = 60



[[main]]
  name = "Site types"
  url = "/site-types/"
  weight = 20

[[main]]
  identifier= "Holidays"
  name = "Holidays"
  url = "/holidays"
  weight="30"

[[main]]
  parent = "Holidays"
  name = "All"
  url = "/holidays"
  weight="30"

[[main]]
  name = "Trips"
  url = "/trips/"
  weight = 40
