[[main]]
  name = "About"
  url = "/pages/about/"
  weight = 60

[[main]]
  name = "Site types"
  url = "/site-types/"
  weight = 20

[[main]]
  name = "Holiday types"
  url = "/holiday-types/"
  weight = 30

[[main]]
  name = "Trips"
  url = "/trips/"
  weight = 40
