baseURL = 'https://travels.loganfamily.co.uk/'
locale = 'en-gb'
title = 'Logan Van Travels'
theme = 'ananke'
summaryLength = 25

[permalinks]
  posts = '/:slug/'
  pages = '/pages/:slug/'

[taxonomies]
  trip = "trips"
  tag = "tags"
  category = "categories"
  site_type = "site-types"

[[menu.main]]
  name = "About"
  url = "/pages/about/"
  weight = 10

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 20

[[menu.main]]
  name = "Site types"
  url = "/site-types/"
  weight = 30

[[menu.main]]
  name = "Trips"
  url = "/trips/"
  weight = 40

[params]
  mainSections = ["posts"]

[params.ananke.pages]
  show_list_images = true
