baseURL = 'https://travels.loganfamily.co.uk/'
locale = 'en-gb'
title = 'Logan Van Travels'
theme = 'ananke'
summaryLength = 25

[permalinks]
  posts = '/:slug/'
  pages = '/pages/:slug/'

[taxonomies]
  campsite = "campsites"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "Campsite types"
  url = "/campsites/"
  weight = 20

[params]
  mainSections = ["posts"]

[params.ananke.pages]
  show_list_images = true
